### PR TITLE
Context specific permissions are not revoked if the studentquiz capability is removed

### PR DESCRIPTION
**Pull request by dionysius**
Implemented according discussion and suggestion in https://github.com/frankkoch/moodle-mod_studentquiz/issues/249

### CODE REVIEW

**Comment by dionysius** [comment]
This PR does not improve the way how often this ensure function is called, I would like to implement a way to listening on events. So far I see, that we would need to listen on:
- added/removed capability event (so existing enrolled roles in the course get the update)
  - but as the function currently states, we need to be careful that we can filter the events, otherwise we create an event loop. Which eventually solves itself - in theory - but I don't know Moodle well enough. We better find a way to filter that.
  - The event a user is enrolled to the course, since for get_roles_used_in_context only roles are returned, which users represent in the course

But I suggest that the event listening part is added by a new PR based on this PR. @timhunt would you mind having a review on this? Thank you in advance

**Comment by timhunt** [comment]
What you have done looks generally good to me. However, it is the end of a long, very hot day, here. So I am not sure how well my brain is working!

I agree with doing the event listening part in a future PR.

The following are the things I noticed.

When defining new capabilities, you can specify 'clonepermissionsfrom'. This means that if people have custom roles set up, you can set a new capability like an exisiting one, which might be even better defaults than the archetypes. E.g. it might be good to clone organize from manage.

Putting $contextcapabilities in db/access.php feels wrong to me. I agree that it is good to move this array to somewhere central. I guess if it was me, I would be gradually moving code out of locallib.php and into auto-loaded classes. So, I might make a class like mod/studentquiz/classes/permission_helper.php, and put all the code related to this, including this array, in there.

Calling a DB function like $DB->get_field in a loop is bad. All pages should be O(1) DB queries. However, deleting questions is hardly the most perforance-critical thing. Might be better to leave this for now. (But please make a new issue so we don't forget. We can probably get Huong to fix that.)

We really should not be using $_REQUEST, but I see that is an existing issue, so now is not the time. Acutally, the way we handle it with mod_studentquiz_helper_get_ids_by_raw_submit is about as good as it can be.

Will be interesting to see what the automated tests say.

I hope those comments are useful.

**Comment by timhunt** [comment]
Also, please may I add a really huge thank-you to you for working on this.

**Comment by dionysius** [comment]
Thank you for your quick response! I hope you can cool down a bit 😄 The suggestions are definitely helpful!

That one big chunk of change just looks like much, but I actually haven't changed what the code does (except adding the right capability check) - I wanted to reduce duplicate code in that function so it is easier to simplify the code in the future.

**Comment by dionysius** [comment]
Forgot to ask: Do you know if I can use `clonepermissionsfrom` without setting archetypes or do both need to exist?

**Comment by timhunt** [comment]
> Forgot to ask: Do you know if I can use `clonepermissionsfrom` without setting `archetypes` or do both need to exist?

You need to set both.

Archetypes are used when someone installs StudenQuiz for the first time.

clonepermissionsfrom will be used only during upgrades, if the other permission you refer to allready existed before the upgrade.

**Comment by dionysius** [comment]
Changes since last review: https://github.com/frankkoch/moodle-mod_studentquiz/compare/3ad5610...permissions

**Pull request closed without merging**
