### PR TITLE
Comment sorting only affects the latest 5 comments

### PR DESCRIPTION
**Pull request by JBThong**

### CODE REVIEW

**Comment by dionysius** [comment]
The pipeline error PSR2.Methods.MethodDeclaration.StaticBeforeVisibility can be ignored, I fixed this already in another PR

**Comment by JBThong** [comment]
Hi @frankkoch,

Currently, the sorting function only sorts the five latest comments, even if the question has more than five comments.
The sorting function should do the sort base on the total comments of the question, not only for the last five comments.
I have fixed this issue in this pull request. Could you help me review it?

Thanks.

**Comment by timhunt** [comment]
I think that the fix does not go far enough. With this change, I think there is no longer having the first if ($haslimit) branch in query_comments. I think the sort order should always be the same, however many comments are being fetched.

Apart from that, I think the patch looks correct.

**Comment by JBThong** [comment]
Hi @timhunt, 

Thanks for your review, I have removed the condition ($haslimit) branch in query_comments. I think it looks better. Could you please help me take a look at it?

Best regards,

**Comment by JBThong** [comment]
Hi Tim,

Thanks for your review, I have removed the condition ($haslimit) branch in query_comments. I think it looks better. Could you please help me take a look at it?

Best regards,

**Pull request merged**
