### PR TITLE
StudentQuiz: fix upgrade/restore performance #139

### PR DESCRIPTION
**Pull request by timhunt**
With a very basic unit test.

Also removed dead code migrate.php.

Thanks to dionysius for some suggestions that have been incorporated here.

### CODE REVIEW

**Comment by timhunt** [comment]
Last night's Travis run failed. The query being tested does not have an ORDER BY, which is good (no need to sort the results, so better for performance not to).

However, this caused the unit test to fail randomly. I have now changed to unit test to be reliable.

The remaining Travis failure above is spurious (the VM failed to initialise properly). If re-run, it should go green.

**Comment by timhunt** [comment]
Last night's Travis run failed. The query being tested does not have an ORDER BY, which is good (no need to sort the results, so better for performance not to).

However, this caused the unit test to fail randomly. I have now changed to unit test to be reliable.

The remaining Travis failure above is spurious (the VM failed to initialise properly). If re-run, it should go green. (It passed for me: https://travis-ci.org/timhunt/moodle-mod_studentquiz/builds/568783737).

**Comment by dionysius** [comment]
I tried to fix the travis behat issue, but it's kinda difficult to prepare the affected table. lets go with `| true` for now

**Comment by timhunt** [comment]
Thanks!

The Behat problem is being worked on in https://tracker.moodle.org/browse/MDL-66378, so hopefully we can remove the | true bit again soon.

**Pull request merged**
