### PR TITLE
Fix 410 upgrade

### PR DESCRIPTION
**Pull request by dionysius**
cc @lamtranb @HuongNV13 'modified' column didn't exist and I didn't catch that https://github.com/frankkoch/moodle-mod_studentquiz/pull/191/files#diff-c74097fbb0a2db56a0a98aaf7d6a2654R564

### CODE REVIEW

**Comment by timhunt** [comment]
Thank you for fixing this.

The odd thing is that this did not break the upgrade for us (we are using Moodle 3.7.4).

**Comment by dionysius** [comment]
@timhunt that is super odd... there is no field 'modified' in this table ...

**Comment by lamtranb** [comment]
Hi @dionysius . 
Thanks for fixing this.

**Comment by dionysius** [comment]
@lamtranb Thank you for the awesome feature! No worries, just wanted to let you know

**Pull request merged**
